name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.KEVIN_DOCKER }}
        DOCKER_PASSWORD: ${{ secrets.KEVIN_PASSWORD }}
      run: 
        echo "Iniciando login"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Fin del login"
        
    - name: Build Docker Images
      run: 
        docker build -t kevinurl/docker-graphql:0.0.2 .
        
    - name: Build Docker Push
      run: 
        docker push kevinurl/docker-graphql:0.0.2
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
